---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-service
  labels:
    death-star-project: social-network
    app-name: user-timeline-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app-name: user-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-service
  labels:
    death-star-project: social-network
    app-name: user-timeline-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: user-timeline-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: user-timeline-service
      name: user-timeline-service
    spec:
      nodeName: userv10
      containers:
      - name: user-timeline-service
        image: gaganso/threadmanager:service_threads
        command: ["UserTimelineService"]
      restartPolicy: Always
