apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: home-timeline-redis
    death-star-project: social-network
  name: home-timeline-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    app-name: compose-post-redis
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: home-timeline-redis
    death-star-project: social-network
  name: home-timeline-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: home-timeline-redis
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: home-timeline-redis
        death-star-project: social-network
      name: home-timeline-redis
    spec:
      containers:
      - args:
        - --maxmemory
        - 49600mb
        - --maxmemory-samples
        - '5'
        - --hz
        - '10'
        - --zset-max-ziplist-entries
        - '128'
        image: redis
        name: home-timeline-redis
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 500Mi
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/azureuser/firm_compass/benchmarks/1-social-network/tmp/home-timeline_redis
          type: Directory
        name: data
