apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: post-storage-service
    death-star-project: social-network
  name: post-storage-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    app-name: post-storage-service
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: post-storage-service
    death-star-project: social-network
  name: post-storage-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: post-storage-service
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: post-storage-service
        death-star-project: social-network
      name: post-storage-service
    spec:
      containers:
      - command:
        - PostStorageService
        image: gaganso/threadmanager:service_threads
        name: post-storage-service
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 500Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/parameters-config.txt
          name: configuration-file
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/azureuser/firm_compass/benchmarks/1-social-network/config/parameters-config.txt
          type: File
        name: configuration-file
