apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: social-graph-redis
    death-star-project: social-network
  name: social-graph-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    app-name: social-graph-redis
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: social-graph-redis
    death-star-project: social-network
  name: social-graph-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: social-graph-redis
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: social-graph-redis
        death-star-project: social-network
      name: social-graph-redis
    spec:
      containers:
      - args:
        - --maxmemory
        - 49600mb
        - --maxmemory-samples
        - '5'
        - --hz
        - '10'
        - --zset-max-ziplist-entries
        - '128'
        image: redis
        name: social-graph-redis
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 500Mi
      restartPolicy: Always
