apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: url-shorten-memcached
    death-star-project: social-network
  name: url-shorten-memcached
  namespace: social-network
spec:
  ports:
  - port: 11211
  selector:
    app-name: url-shorten-memcached
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: url-shorten-memcached
    death-star-project: social-network
  name: url-shorten-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: url-shorten-memcached
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: url-shorten-memcached
        death-star-project: social-network
      name: url-shorten-memcached
    spec:
      containers:
      - args:
        - -m
        - '64'
        - -c
        - '1024'
        - -R
        - '20'
        - -t
        - '4'
        - -f
        - '1.25'
        image: memcached
        name: url-shorten-memcached
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 500Mi
      restartPolicy: Always
