apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: user-mongodb
    death-star-project: social-network
  name: user-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    app-name: user-mongodb
    death-star-project: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: user-mongodb
    death-star-project: social-network
  name: user-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: user-mongodb
      death-star-project: social-network
  template:
    metadata:
      labels:
        app-name: user-mongodb
        death-star-project: social-network
      name: user-mongodb
    spec:
      containers:
      - args:
        - --wiredTigerCacheSizeGB
        - '30.5'
        - --setParameter
        - wiredTigerConcurrentReadTransactions=128
        - --setParameter
        - wiredTigerConcurrentWriteTransactions=128
        image: mongo:4.2
        name: user-mongodb
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 500Mi
      restartPolicy: Always
